### ISSUE TITLE
unable to import with 7.1+

### ISSUE THREAD

**Issue by hhellbusch** [gpe-mw-training/bxms_decision_mgmt_foundations_lab#7]
![image](https://user-images.githubusercontent.com/2072460/52588550-b9025800-2e0a-11e9-9cb0-f2b28dce6d95.png)

**Comment by btison** [comment]
This is caused by a bug in 7.1
When you import the repository from github, add (bogus) credentials in the 'advanced' section. After that you should be able to import the projects in the repo

**Comment by borysmarceloherrera** [comment]
Thanks a lot! I was struggling into looking for a solution or any other branch that could use 7.1 Decision Manager version.
